[package]
name = "shura"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/AndriBaal/shura"
documentation = "https://docs.rs/shura"
readme = "README.md"
license = "Apache-2.0"
description = "A fast cross-plattform 2D component-based game framework"
keywords = ["graphics", "physics", "game", "android", "wasm"]
categories = [
    "wasm",
    "rendering::engine",
    "graphics",
    "game-engines",
    "game-development",
]
exclude = ["arch_android_setup.sh", "docs"]

[features]
animation = []
gamepad = ["dep:gilrs"]
text = ["dep:wgpu_glyph"]
audio = ["dep:rodio"]
physics = ["dep:rapier2d"]
gui = ["dep:egui", "dep:egui-wgpu", "dep:egui-winit"]
log = ["dep:log"]
serde = [
    "dep:serde",
    "dep:bincode",
    "wgpu/trace",
    "wgpu/serde",
    "wgpu/replay",
    "gilrs?/serde-serialize",
    "egui?/serde",
    "nalgebra/serde-serialize",
    "rapier2d?/serde-serialize",
]
default = ["animation", "gamepad", "text", "audio", "physics", "gui", "serde", "log"]

[lib]
crate-type = ["lib", "cdylib"]


[dependencies]
env_logger="0.10"
delaunator = "1"
mint = { version = "0.5.6" }
nalgebra = { version = "0.32.1", features = ["convert-bytemuck", "mint"] }
wgpu_glyph = { version = "0.19.0", optional = true }
gilrs = { version = "0.10.1", optional = true }
naga = "0.11.0"
egui-winit = { version = "0.21", optional = true }
egui-wgpu = { version = "0.21", features = ["winit"], optional = true }
egui = { version = "0.21", default-features = false, optional = true, features = [
    "bytemuck",
    "tracing",
    "default_fonts",
    "mint",
] }
rapier2d = { version = "0.17", optional = true }
log = {version="0.4", optional=true, features=["std"]}
downcast-rs = "1.2.0"
rustc-hash = "1.1"
futures-intrusive = "0.5.0"
pollster = "0.3.0"
bytemuck = { version = "1.12.2", features = ["derive"] }
instant = "0.1.12"
shura_proc = { path = "../shura_proc" }
crossbeam = "0.8.2"
image = { version = "0.23.14", default-features = false, features = [
    "png",
    "jpeg",
] } # Bgra Format is missing in newer versions
serde = { version = "1", features = ["derive", "rc"], optional = true }
bincode = { version = "1.3.3", optional = true }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { version = "0.15", features = ["glsl"] }
rodio = { version = "0.17", default-features = false, optional = true, features = [
    "symphonia-all",
] }


[target.'cfg(target_arch = "wasm32")'.dependencies]
rodio = { version = "0.17", features = [
    "wasm-bindgen",
    "symphonia-all",
], default-features = false, optional = true }
console_error_panic_hook = "0.1"
wgpu = { version = "0.15", features = ["webgl", "glsl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Window", "Element", "console"] }

[dev-dependencies]
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.28", features = ["mint", "android-native-activity"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
winit = { version = "0.28", features = ["mint"] }
