[package]
name = "shura"
version = "0.1.3"
edition = "2021"
repository = "https://github.com/AndriBaal/shura"
documentation = "https://docs.rs/shura"
readme = "README.md"
license = "Apache-2.0"
description = "A fast cross-plattform 2D component-based game framework"
keywords = ["graphics", "physics", "game", "android", "wasm"]
categories = [
    "wasm",
    "rendering::engine",
    "graphics",
    "game-engines",
    "game-development"
]
exclude = ["arch_android_setup.sh"]

[features]
gamepad = ["dep:gilrs"]
text = ["dep:wgpu_glyph"]
audio = ["dep:rodio"]
physics = ["dep:rapier2d"]
gui = ["dep:egui", "dep:egui_wgpu_backend", "dep:egui_winit_platform"]
default = ["audio", "physics", "gui", "text", "gamepad"]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
nalgebra = { version = "0.31.4", features = ["convert-bytemuck"] }
wgpu_glyph = { version = "0.18.0", optional = true }
gilrs = { version = "0.10.1", optional = true }
naga = "0.10.0"
egui_winit_platform = { version = "0.16", optional = true }
egui = { version = "0.19.0", default-features = false, optional = true, features = [
    "bytemuck",
    "tracing",
] }
rapier2d = { version = "0.16.0", optional = true }
log = "0.4.17"
downcast-rs = "1.2.0"
winit = { version = "0.27.5" }
rustc-hash = "1.1"
futures-intrusive = "0.5.0"
pollster = "0.2.5"
bytemuck = { version = "1.12.2", features = ["derive"] }
instant = "0.1.12"
shura_proc = "0.1.0"
crossbeam = "0.8.2"
image = { version = "0.23.14", default-features = false, features = [
    "png",
    "jpeg",
] } # Bgra Format is missing in newer versions


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui_wgpu_backend = { version = "0.20.0", optional = true }
env_logger = "0.10.0"
wgpu = { version = "0.14.0", features = ["glsl"] }
rodio = { version = "0.16.0", default-features = false, optional = true, features = [
    "symphonia-all",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
egui_wgpu_backend = { version = "0.20.0", optional = true, features = ["web"] }
getrandom = { version = "0.2", features = ["js"] }
rodio = { version = "0.16.0", features = [
    "wasm-bindgen",
    "symphonia-all",
], default-features = false, optional = true }
console_error_panic_hook = "0.1"
wasm-logger = "0.2"
wgpu = { version = "0.14.0", features = ["webgl", "glsl"] }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = { version = "0.3", features = ["Document", "Window", "Element"] }
